SELECT * FROM ADMIN

SELECT * FROM DEVICE

INSERT INTO MENU(menu_id,CATEGORY_ID,MENU_NAME,PRICE,FILE_NAME)
VALUES(seq_admin.nextval,1,'카푸치노',4000,'f3')

INSERT INTO MENU(menu_id,CATEGORY_ID,MENU_NAME,PRICE,FILE_NAME)
VALUES(seq_admin.nextval,1,'콜드브루',4000,'f3')

UPDATE menu SET CATEGORY_ID =1 
SELECT * FROM MENU

SELECT * FROM STOCK


DELETE FROM stock

