SELECT * FROM menu;

INSERT INTO CATEGORY(CATEGORY_id,CATEGORY_NAME)
VALUES(2,'디저트')

INSERT INTO CATEGORY(CATEGORY_id,CATEGORY_NAME)
VALUES(3,'음료')

INSERT INTO menu(menu_id,MENU_NAME,CATEGORY_ID,PRICE,FILE_NAME)
VALUES(seq_menu.nextval,'딸기 타르트',2,'6000','f6')

INSERT INTO menu(menu_id,MENU_NAME,CATEGORY_ID,PRICE,FILE_NAME)
VALUES(seq_menu.nextval,'아이스아메리카노',1,'2000','f7')

INSERT INTO menu(menu_id,MENU_NAME,CATEGORY_ID,PRICE,FILE_NAME)
VALUES(seq_menu.nextval,'아이스티',3,'3000','f8')
INSERT INTO menu(menu_id,MENU_NAME,CATEGORY_ID,PRICE,FILE_NAME)
VALUES(seq_menu.nextval,'주스',3,'2000','f9')

SELECT * FROM STOCK

SELECT * FROM CATEGORY

DELETE FROM CATEGORY WHERE CATEGORY_ID>1

stock.getMenu.category.